MODEL:
  META_ARCHITECTURE: "Dance"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOSE"
DATASETS:
  TRAIN: ("coco_2017_train_edge",)
  TEST: ("coco_2017_val_edge",)
SOLVER:
  IMS_PER_BATCH: 8 # 2 GPUs or 4 GPUs
  BASE_LR: 0.005
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 20000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
