model: 'rcnn'
network: 'rcnn_34'
task: 'rcnn_dance'
resume: true
gpus: (0, 1, 2)

det_model: 'rcnn_det'

train:
    optim: 'adam'
    lr: 1e-5
    scheduler: 'warmupcosine'
    gamma: 0.5
    batch_size: 27
    dataset: 'CityscapesTrain'
    num_workers: 32
    epoch: 250
test:
    dataset: 'CityscapesCocoVal'
    batch_size: 1

# eval_ep: 1

heads: {'act_hm': 8, 'awh': 2}
segm_or_bbox: 'segm'
ct_score: 0.03
