_BASE_: "Base-dance.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  DANCE:
    EDGE:
      IN_FEATURES: ['p2', 'p3', 'p4', 'p5']
    HEAD:
      NUM_SAMPLING: 196
OUTPUT_DIR: "output/r50_1x/"
